# Keep upstream's generic options local to this function, away from SDK options.
function(ewrtc_add_libjuice)
  set(BUILD_SHARED_LIBS OFF)
  set(NO_SERVER ON)
  set(NO_TESTS ON)
  set(CMAKE_POLICY_DEFAULT_CMP0077 NEW)
  add_subdirectory("${EWRTC_LIBJUICE_SOURCE_DIR}" "${CMAKE_CURRENT_BINARY_DIR}/third_party/libjuice" EXCLUDE_FROM_ALL)
endfunction()

# Accept the former FetchContent override for existing integrators.
if(FETCHCONTENT_SOURCE_DIR_LIBJUICE AND NOT EWRTC_LIBJUICE_SOURCE_DIR)
  set(EWRTC_LIBJUICE_SOURCE_DIR "${FETCHCONTENT_SOURCE_DIR_LIBJUICE}" CACHE PATH "Local libjuice source directory")
endif()
set(EWRTC_LIBJUICE_SOURCE_DIR "${PROJECT_SOURCE_DIR}/third_party/libjuice" CACHE PATH "Local libjuice source directory")
if(NOT EXISTS "${EWRTC_LIBJUICE_SOURCE_DIR}/CMakeLists.txt")
  message(FATAL_ERROR "libjuice source is missing. Run git submodule update --init --recursive third_party/libjuice, or set EWRTC_LIBJUICE_SOURCE_DIR.")
endif()
if(EWRTC_ENFORCE_DEPENDENCY_LOCK)
  find_package(Git REQUIRED)
  # The gitlink is the source of truth, including a staged dependency upgrade.
  execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${PROJECT_SOURCE_DIR}" ls-files --stage -- third_party/libjuice
    OUTPUT_VARIABLE gitlink RESULT_VARIABLE lock_result OUTPUT_STRIP_TRAILING_WHITESPACE)
  execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${EWRTC_LIBJUICE_SOURCE_DIR}" rev-parse HEAD
    OUTPUT_VARIABLE revision RESULT_VARIABLE revision_result OUTPUT_STRIP_TRAILING_WHITESPACE)
  if(NOT lock_result EQUAL 0 OR NOT revision_result EQUAL 0 OR NOT gitlink MATCHES "^160000 ([0-9a-f]+) 0")
    message(FATAL_ERROR "Cannot verify libjuice against the repository gitlink; dependency lock requires Git checkouts.")
  endif()
  if(NOT revision STREQUAL CMAKE_MATCH_1)
    message(FATAL_ERROR "libjuice must match the third_party/libjuice gitlink (${CMAKE_MATCH_1}); found ${revision}")
  endif()
endif()
ewrtc_add_libjuice()
set_target_properties(juice PROPERTIES EXCLUDE_FROM_ALL TRUE C_EXTENSIONS ON)
set_target_properties(juice-static PROPERTIES C_EXTENSIONS ON)
if(session IN_LIST enabled)
  set_target_properties(juice-static PROPERTIES EXPORT_NAME _libjuice)
  install(TARGETS juice-static EXPORT ewrtcTargets ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR})
endif()
set(ice_libs juice-static)
