set(need_crypto FALSE)
set(need_srtp FALSE)
set(need_threads FALSE)
set(need_juice FALSE)
if(crypto IN_LIST enabled OR dtls IN_LIST enabled)
  set(need_crypto TRUE)
  if(EWRTC_WITH_OPENSSL)
    set(openssl_components Crypto)
    if(dtls IN_LIST enabled)
      list(APPEND openssl_components SSL)
    endif()
    find_package(OpenSSL 1.1.1 EXACT REQUIRED COMPONENTS ${openssl_components})
    # CMake's numeric version comparison does not distinguish letter patches.
    if(NOT OPENSSL_VERSION STREQUAL "1.1.1w")
      message(FATAL_ERROR "OpenSSL 1.1.1w is required; found ${OPENSSL_VERSION}. Set OPENSSL_ROOT_DIR to the 1.1.1w installation and use a fresh build directory.")
    endif()
    list(APPEND crypto_libs OpenSSL::Crypto)
    list(APPEND dtls_libs OpenSSL::SSL OpenSSL::Crypto)
  endif()
  if(EWRTC_WITH_MBEDTLS)
    find_package(PkgConfig REQUIRED)
    if(EWRTC_ENFORCE_DEPENDENCY_LOCK)
      pkg_check_modules(MBEDCRYPTO REQUIRED IMPORTED_TARGET mbedcrypto=3.6.5)
    else()
      pkg_check_modules(MBEDCRYPTO REQUIRED IMPORTED_TARGET mbedcrypto>=3.6)
    endif()
    list(APPEND crypto_libs PkgConfig::MBEDCRYPTO)
    if(dtls IN_LIST enabled)
      pkg_check_modules(MBEDTLS REQUIRED IMPORTED_TARGET mbedtls)
      pkg_check_modules(MBEDX509 REQUIRED IMPORTED_TARGET mbedx509)
      list(APPEND dtls_libs PkgConfig::MBEDTLS PkgConfig::MBEDX509 PkgConfig::MBEDCRYPTO)
    endif()
  endif()
endif()
if(srtp IN_LIST enabled)
  set(need_srtp TRUE)
  find_package(PkgConfig REQUIRED)
  if(EWRTC_ENFORCE_DEPENDENCY_LOCK)
    pkg_check_modules(SRTP REQUIRED IMPORTED_TARGET libsrtp2=2.7.0)
  else()
    pkg_check_modules(SRTP REQUIRED IMPORTED_TARGET libsrtp2>=2.5)
  endif()
  set(srtp_libs PkgConfig::SRTP)
endif()
if(pal_linux IN_LIST enabled)
  if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
    message(FATAL_ERROR "pal_linux is Linux only; build portable components with your own PAL")
  endif()
  set(need_threads TRUE)
  find_package(Threads REQUIRED)
  set(pal_linux_libs Threads::Threads)
endif()
if(ice IN_LIST enabled AND EWRTC_WITH_LIBJUICE)
  set(need_juice TRUE)
  set(need_threads TRUE)
  find_package(Threads REQUIRED)
  include(FetchContent)
  set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
  set(NO_SERVER ON CACHE BOOL "" FORCE)
  set(NO_TESTS ON CACHE BOOL "" FORCE)
  set(EWRTC_LIBJUICE_COMMIT 6d0356d092701dcce1f731559d38dc94f52eeb14)
  FetchContent_Declare(libjuice GIT_REPOSITORY https://github.com/paullouisageneau/libjuice.git GIT_TAG ${EWRTC_LIBJUICE_COMMIT})
  FetchContent_MakeAvailable(libjuice)
  set_property(DIRECTORY "${libjuice_SOURCE_DIR}" PROPERTY EXCLUDE_FROM_ALL TRUE)
  if(EWRTC_ENFORCE_DEPENDENCY_LOCK)
    execute_process(COMMAND git -C "${libjuice_SOURCE_DIR}" rev-parse HEAD OUTPUT_VARIABLE revision OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT revision STREQUAL EWRTC_LIBJUICE_COMMIT)
      message(FATAL_ERROR "libjuice must be ${EWRTC_LIBJUICE_COMMIT}")
    endif()
  endif()
  set_target_properties(juice PROPERTIES EXCLUDE_FROM_ALL TRUE C_EXTENSIONS ON)
  set_target_properties(juice-static PROPERTIES C_EXTENSIONS ON)
  # Export the static variant with our package; upstream exports only juice.
  if(session IN_LIST enabled)
    set_target_properties(juice-static PROPERTIES EXPORT_NAME _libjuice)
    install(TARGETS juice-static EXPORT ewrtcTargets ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR})
  endif()
  set(ice_libs juice-static)
endif()
