if(EWRTC_BUILD_TESTS)
  enable_testing()
  find_package(Python3 COMPONENTS Interpreter QUIET)
  if(Python3_Interpreter_FOUND)
    add_test(NAME architecture COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/check_architecture.py)
  endif()
  add_executable(ewrtc_component_tests tests/test_components.c)
  target_link_libraries(ewrtc_component_tests PRIVATE ewrtc_common)
  foreach(c pal crypto sdp stun dtls rtp media srtp)
    string(TOUPPER "${c}" upper)
    if(c IN_LIST enabled)
      target_compile_definitions(ewrtc_component_tests PRIVATE HAVE_${upper}=1)
      target_link_libraries(ewrtc_component_tests PRIVATE ewrtc_${c})
    endif()
  endforeach()
  if(CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
    target_compile_options(ewrtc_component_tests PRIVATE -UNDEBUG)
  endif()
  add_test(NAME components COMMAND ewrtc_component_tests)
  if(dtls IN_LIST enabled AND EWRTC_WITH_OPENSSL)
    add_executable(ewrtc_openssl_bio_tests tests/test_openssl_bio.c)
    target_link_libraries(ewrtc_openssl_bio_tests PRIVATE ewrtc_dtls)
    target_compile_options(ewrtc_openssl_bio_tests PRIVATE -UNDEBUG)
    add_test(NAME openssl_bio COMMAND ewrtc_openssl_bio_tests)
    if(pal_linux IN_LIST enabled)
      add_executable(ewrtc_dtls_transport_tests tests/test_dtls_transport.c)
      target_link_libraries(ewrtc_dtls_transport_tests PRIVATE ewrtc_dtls ewrtc_pal_linux)
      target_compile_options(ewrtc_dtls_transport_tests PRIVATE -UNDEBUG)
      add_test(NAME dtls_transport COMMAND ewrtc_dtls_transport_tests)
      set_tests_properties(dtls_transport PROPERTIES TIMEOUT 15)
    endif()
  endif()
  if(sdp IN_LIST enabled)
    add_executable(ewrtc_sdp_negotiation_tests tests/test_sdp_negotiation.c)
    target_link_libraries(ewrtc_sdp_negotiation_tests PRIVATE ewrtc_sdp)
    target_compile_options(ewrtc_sdp_negotiation_tests PRIVATE -UNDEBUG)
    add_test(NAME sdp_negotiation COMMAND ewrtc_sdp_negotiation_tests)
  endif()
  if(media IN_LIST enabled)
    add_executable(ewrtc_receive_tests tests/test_receive.c)
    target_link_libraries(ewrtc_receive_tests PRIVATE ewrtc_media)
    target_compile_options(ewrtc_receive_tests PRIVATE -UNDEBUG)
    add_test(NAME receive COMMAND ewrtc_receive_tests)
  endif()
  if(session IN_LIST enabled AND EWRTC_WITH_NATIVE_ICE)
    add_executable(ewrtc_custom_pal_tests tests/test_custom_pal.c)
    target_link_libraries(ewrtc_custom_pal_tests PRIVATE ewrtc_session)
    target_compile_options(ewrtc_custom_pal_tests PRIVATE -UNDEBUG)
    add_test(NAME custom_pal COMMAND ewrtc_custom_pal_tests)
  endif()
  if(turn IN_LIST enabled)
    add_executable(ewrtc_turn_tests tests/test_turn.c)
    target_link_libraries(ewrtc_turn_tests PRIVATE ewrtc_turn)
    target_compile_options(ewrtc_turn_tests PRIVATE -UNDEBUG)
    add_test(NAME turn COMMAND ewrtc_turn_tests)
  endif()
  if(session IN_LIST enabled AND pal_linux IN_LIST enabled)
    add_executable(ewrtc_tests tests/test_protocol.c)
    target_compile_definitions(ewrtc_tests PRIVATE ${definitions} _POSIX_C_SOURCE=200809L)
    target_link_libraries(ewrtc_tests PRIVATE ewrtc ewrtc_pal_linux)
    if(CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
      target_compile_options(ewrtc_tests PRIVATE -UNDEBUG)
    endif()
    add_test(NAME protocol COMMAND ewrtc_tests)
    add_executable(ewrtc_negotiation_tests tests/test_negotiation.c)
    target_compile_definitions(ewrtc_negotiation_tests PRIVATE ${definitions})
    target_compile_options(ewrtc_negotiation_tests PRIVATE -UNDEBUG)
    target_link_libraries(ewrtc_negotiation_tests PRIVATE ewrtc ewrtc_pal_linux)
    add_test(NAME negotiation COMMAND ewrtc_negotiation_tests)
    set_tests_properties(negotiation PROPERTIES TIMEOUT 120)
    add_executable(ewrtc_context_tests tests/test_context.c)
    target_compile_definitions(ewrtc_context_tests PRIVATE ${definitions})
    target_compile_options(ewrtc_context_tests PRIVATE -UNDEBUG)
    target_link_libraries(ewrtc_context_tests PRIVATE ewrtc ewrtc_pal_linux Threads::Threads ${CMAKE_DL_LIBS})
    add_test(NAME context COMMAND ewrtc_context_tests)
    set_tests_properties(context PROPERTIES TIMEOUT 120)
    add_executable(ewrtc_runtime_tests tests/test_runtime.c)
    target_compile_definitions(ewrtc_runtime_tests PRIVATE ${definitions})
    target_compile_options(ewrtc_runtime_tests PRIVATE -UNDEBUG)
    target_link_libraries(ewrtc_runtime_tests PRIVATE ewrtc ewrtc_pal_linux Threads::Threads)
    add_test(NAME runtime COMMAND ewrtc_runtime_tests)
  endif()
endif()
if(EWRTC_BUILD_TESTS)
  get_property(test_targets DIRECTORY PROPERTY BUILDSYSTEM_TARGETS)
  foreach(target IN LISTS test_targets)
    if(target MATCHES "^ewrtc_.*tests$")
      target_include_directories(${target} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/src)
    endif()
  endforeach()
endif()
