option(EWRTC_BUILD_INTERNAL_EXAMPLES "Build internal protocol development examples" OFF)
if(EWRTC_BUILD_INTERNAL_EXAMPLES)
  add_subdirectory(examples/components)
endif()
if(EWRTC_BUILD_EXAMPLES AND session IN_LIST enabled AND pal_linux IN_LIST enabled)
  include(${CMAKE_CURRENT_LIST_DIR}/dependencies/Opus.cmake)
  add_executable(ewrtc_demo examples/demo.c)
  target_compile_definitions(ewrtc_demo PRIVATE _POSIX_C_SOURCE=200809L)
  target_link_libraries(ewrtc_demo PRIVATE ewrtc::ewrtc ewrtc::pal_linux PkgConfig::OPUS)
endif()
