# Only application and platform integration targets form the installed SDK.
set(export_session FALSE)
set(export_linux FALSE)
set(public_components "")
if(session IN_LIST enabled)
  set(export_session TRUE)
  list(APPEND public_components ewrtc session)
  # Keep the application-facing Session spelling without exporting its internals.
  add_library(ewrtc_session_api INTERFACE)
  set_target_properties(ewrtc_session_api PROPERTIES EXPORT_NAME session)
  target_link_libraries(ewrtc_session_api INTERFACE ewrtc)
  add_library(ewrtc::session ALIAS ewrtc_session_api)
  install(TARGETS ewrtc_session_api EXPORT ewrtcTargets)
endif()
if(pal_linux IN_LIST enabled)
  set(export_linux TRUE)
  list(APPEND public_components pal_linux)
  set_target_properties(ewrtc_pal_linux PROPERTIES EXPORT_NAME pal_linux)
  add_library(ewrtc::pal_linux ALIAS ewrtc_pal_linux)
  install(TARGETS ewrtc_pal_linux EXPORT ewrtcTargets ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR})
endif()
if(public_components)
  install(FILES LICENSE THIRD_PARTY_NOTICES.md DESTINATION ${CMAKE_INSTALL_DATADIR}/ewrtc)
  install(DIRECTORY include/ewrtc/ DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/ewrtc
    PATTERN "platform" EXCLUDE)
  if(export_session)
    install(FILES include/ewrtc.h DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
  endif()
  if(export_linux)
    install(FILES include/ewrtc/platform/linux.h DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/ewrtc/platform)
  endif()
  configure_package_config_file(cmake/ewrtcConfig.cmake.in ${CMAKE_CURRENT_BINARY_DIR}/ewrtcConfig.cmake INSTALL_DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/ewrtc)
  write_basic_package_version_file(${CMAKE_CURRENT_BINARY_DIR}/ewrtcConfigVersion.cmake VERSION ${PROJECT_VERSION} COMPATIBILITY SameMinorVersion)
  install(EXPORT ewrtcTargets NAMESPACE ewrtc:: DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/ewrtc)
  install(FILES ${CMAKE_CURRENT_BINARY_DIR}/ewrtcConfig.cmake ${CMAKE_CURRENT_BINARY_DIR}/ewrtcConfigVersion.cmake DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/ewrtc)
else()
  # Reconfiguring an existing build as internal-only must not leave a usable package.
  file(REMOVE ${CMAKE_CURRENT_BINARY_DIR}/ewrtcConfig.cmake ${CMAKE_CURRENT_BINARY_DIR}/ewrtcConfigVersion.cmake)
endif()
