set(need_crypto FALSE)
set(need_srtp FALSE)
set(need_threads FALSE)
set(need_juice FALSE)
if(crypto IN_LIST enabled OR dtls IN_LIST enabled)
  set(need_crypto TRUE)
  if(EWRTC_WITH_OPENSSL)
    include(${CMAKE_CURRENT_LIST_DIR}/dependencies/OpenSSL.cmake)
  endif()
  if(EWRTC_WITH_MBEDTLS)
    include(${CMAKE_CURRENT_LIST_DIR}/dependencies/MbedTLS.cmake)
  endif()
endif()
if(srtp IN_LIST enabled)
  set(need_srtp TRUE)
  include(${CMAKE_CURRENT_LIST_DIR}/dependencies/SRTP.cmake)
endif()
if(pal_linux IN_LIST enabled)
  if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
    message(FATAL_ERROR "pal_linux is Linux only; build portable components with your own PAL")
  endif()
  set(need_threads TRUE)
  find_package(Threads REQUIRED)
  set(pal_linux_libs Threads::Threads)
endif()
if(ice IN_LIST enabled AND EWRTC_WITH_LIBJUICE)
  set(need_juice TRUE)
  set(need_threads TRUE)
  find_package(Threads REQUIRED)
  include(${CMAKE_CURRENT_LIST_DIR}/dependencies/Libjuice.cmake)
endif()
