set(deps_common "")
set(deps_pal common)
set(deps_pal_linux pal)
set(deps_crypto common)
set(deps_sdp pal)
set(deps_stun pal crypto)
set(deps_turn pal stun crypto)
set(deps_ice pal)
if(EWRTC_WITH_NATIVE_ICE)
  list(APPEND deps_ice stun turn)
endif()
set(deps_dtls pal)
set(deps_srtp pal)
set(deps_rtp common)
set(deps_media pal rtp)
set(deps_session pal crypto sdp ice dtls srtp media)
set(all_components common pal pal_linux crypto sdp stun turn ice dtls srtp rtp media session)
set(enabled ${EWRTC_COMPONENTS})
if(EWRTC_WITH_LINUX_PAL AND session IN_LIST enabled)
  list(APPEND enabled pal_linux)
endif()
foreach(c IN LISTS enabled)
  if(NOT c IN_LIST all_components)
    message(FATAL_ERROR "Unknown EWRTC component: ${c}")
  endif()
endforeach()
foreach(pass RANGE 1 12)
  foreach(c IN LISTS enabled)
    list(APPEND enabled ${deps_${c}})
  endforeach()
  list(REMOVE_DUPLICATES enabled)
endforeach()
message(STATUS "ewrtc enabled components: ${enabled}")
if(ice IN_LIST enabled AND NOT EWRTC_WITH_NATIVE_ICE AND NOT EWRTC_WITH_LIBJUICE)
  message(FATAL_ERROR "ICE requires at least one backend")
endif()
if((crypto IN_LIST enabled OR dtls IN_LIST enabled) AND NOT EWRTC_WITH_OPENSSL AND NOT EWRTC_WITH_MBEDTLS)
  message(FATAL_ERROR "Crypto/DTLS requires at least one backend")
endif()

set(src_common src/common/common.c)
set(src_pal src/pal/pal.c src/pal/log.c)
set(src_pal_linux src/platform/linux.c)
set(src_crypto src/crypto/crypto.c)
if(EWRTC_WITH_OPENSSL)
  list(APPEND src_crypto src/crypto/openssl.c)
endif()
if(EWRTC_WITH_MBEDTLS)
  list(APPEND src_crypto src/crypto/mbedtls.c)
endif()
set(src_sdp src/sdp/sdp.c)
set(src_stun src/stun/stun.c)
set(src_turn src/turn/turn.c)
set(src_ice src/ice/ice.c)
if(EWRTC_WITH_NATIVE_ICE)
  list(APPEND src_ice src/ice/native.c)
endif()
if(EWRTC_WITH_LIBJUICE)
  list(APPEND src_ice src/ice/juice.c)
endif()
set(src_dtls src/dtls/dtls.c)
if(EWRTC_WITH_OPENSSL)
  list(APPEND src_dtls src/dtls/openssl.c src/dtls/openssl_bio.c)
endif()
if(EWRTC_WITH_MBEDTLS)
  list(APPEND src_dtls src/dtls/mbedtls.c)
endif()
set(src_srtp src/srtp/srtp.c)
set(src_rtp src/rtp/rtp.c)
set(src_media src/media/media.c src/media/receive.c src/media/packet.c src/media/h264.c src/media/opus.c src/media/feedback.c src/media/cache.c)
set(src_session src/session/log.c src/session/context.c src/session/queue.c src/session/prepare.c src/session/session.c src/session/runtime.c src/session/connection.c src/session/stats.c)
set(definitions EWRTC_LOG_MIN_LEVEL=${EWRTC_LOG_MIN_LEVEL} EWRTC_WITH_LINUX_PAL=$<BOOL:${EWRTC_WITH_LINUX_PAL}> EWRTC_WITH_NATIVE_ICE=$<BOOL:${EWRTC_WITH_NATIVE_ICE}> EWRTC_WITH_LIBJUICE=$<BOOL:${EWRTC_WITH_LIBJUICE}> EWRTC_WITH_OPENSSL=$<BOOL:${EWRTC_WITH_OPENSSL}> EWRTC_WITH_MBEDTLS=$<BOOL:${EWRTC_WITH_MBEDTLS}>)
