set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
if(NOT DEFINED ENV{LUCKFOX_TOOLCHAIN})
  message(FATAL_ERROR "Set LUCKFOX_TOOLCHAIN to the arm-rockchip830-linux-uclibcgnueabihf directory")
endif()
set(_cross "$ENV{LUCKFOX_TOOLCHAIN}/bin/arm-rockchip830-linux-uclibcgnueabihf")
set(CMAKE_C_COMPILER "${_cross}-gcc")
set(CMAKE_CXX_COMPILER "${_cross}-g++")
set(CMAKE_STRIP "${_cross}-strip")
set(CMAKE_C_FLAGS_INIT "-mcpu=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard")
set(CMAKE_CXX_FLAGS_INIT "${CMAKE_C_FLAGS_INIT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
